CREATE TABLE ole.Buyer (
    bs_id int IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Code varchar(10),
	bs_name varchar(60),
	bs_abbreviation varchar(5),
    billing_addr varchar(300),
	delivery_addr varchar(300),
    city varchar(50),
    pincode varchar(50),
    country varchar(20),
	currency varchar(5),
    bs_code varchar(4),
    contact_person varchar(50),
	mobile_ext varchar(3),
    mobile varchar(50),
	phone varchar(50),
    email varchar(200),
	username varchar(20),
    entDate datetime DEFAULT getdate(),
);

INSERT INTO ole.Buyer (
    Code,
    bs_name,
    bs_abbreviation,
    billing_addr,
    delivery_addr,
    city,
    pincode,
    country,
    currency,
    bs_code,
    contact_person,
    mobile_ext,
    mobile,
    phone,
    email,
    username,
) values ('000 0001', 'G & P Leather', 'GPL', 'G & P Leather, 1/1, 1st Floor, 1st Cross, 1st Main, 1st Stage, Peenya Industrial Estate, Bangalore - 560058', 'G & P Leather, 1/1, 1st Floor, 1st Cross, 1st Main, 1st Stage, Peenya Industrial Estate, Bangalore - 560058', 'Bangalore', '560058', 'India', 'INR', '0001', 'Mr. Prakash', '91', '9845012345', '080-28396000', ' ', '    ', 'admin')

{
    "Code": "000 0001",
    "bs_name": "G & P Leather",
    "bs_abbreviation": "GPL",
    "billing_addr": "G & P Leather, 1/1, 1st Floor, 1st Cross, 1st Main, 1st Stage, Peenya Industrial Estate, Bangalore - 560058",
    "delivery_addr": "G & P Leather, 1/1, 1st Floor, 1st Cross, 1st Main, 1st Stage, Peenya Industrial Estate, Bangalore - 560058",
    "city": "Bangalore",
    "pincode": "560058",
    "country": "India",
    "currency": "INR",
    "bs_code": "0001",
    "contact_person": "Mr. Prakash",
    "mobile_ext": "91",
    "mobile": "9845012345",
    "phone": "080-28396000",
    "email": " ",
    "username": "    "
}